/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bob.glb --transform --types 
Files: Bob.glb [189.2KB] > /Users/user/Desktop/Projects/wealthforge/public/Bob-transformed.glb [31KB] (84%)
*/

import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    "Head_Cube-Mesh": THREE.Mesh
    "Head_Cube-Mesh_1": THREE.Mesh
    Eyes_Sphere: THREE.Mesh
    Tooth_Cube001: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    Pink: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
    Tooth: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Bob-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Eyes_Sphere.geometry} material={materials.Eyes} />
      <mesh geometry={nodes.Tooth_Cube001.geometry} material={materials.Tooth} />
      <mesh geometry={nodes['Head_Cube-Mesh'].geometry} material={materials.Material} />
      <mesh geometry={nodes['Head_Cube-Mesh_1'].geometry} material={materials.Pink} />
    </group>
  )
}

useGLTF.preload('/models/Bob-transformed.glb')
