/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Goose.glb --transform --types 
Files: Goose.glb [33.5KB] > /Users/user/Desktop/Projects/wealthforge/public/Goose-transformed.glb [5.14KB] (85%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Geo_Goose: THREE.Mesh
  }
  materials: {
    lambert2SG: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Goose-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geo_Goose.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/models/Goose-transformed.glb')
